version: '2.2'
x-net: &net
  networks:
      - main
services:
  app:
    <<: *net
    image: datajoint/pydev:${PY_VER}-alpine${ALPINE_VER}
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      fakeservices.datajoint.io:
        condition: service_healthy
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - DJ_TEST_HOST=db
      - DJ_TEST_USER=datajoint
      - DJ_TEST_PASSWORD=datajoint
      - S3_ENDPOINT=fakeservices.datajoint.io:9000
      - S3_ACCESS_KEY=datajoint
      - S3_SECRET_KEY=datajoint
      - S3_BUCKET=datajoint-test
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=datajoint
      - DISPLAY
      - COVERALLS_SERVICE_NAME
      - COVERALLS_REPO_TOKEN
    working_dir: /src
    command: >
      /bin/sh -c
       "
        pip install --user nose nose-cov coveralls .;
        pip freeze | grep datajoint;
        coveralls;
        nosetests -vsw tests --with-coverage --cover-package=datajoint;
        # jupyter notebook;
       "
    # ports:
    #   - "8888:8888"
    user: ${UID}:${GID}
    volumes:
      - .:/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ./notebooks:/home/dja/notebooks
  db:
    <<: *net
    image: datajoint/mysql:$MYSQL_VER
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    # ports:
    #   - "3306:3306"
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
  minio:
    <<: *net
    environment:
      - MINIO_ACCESS_KEY=datajoint
      - MINIO_SECRET_KEY=datajoint
    image: minio/minio:$MINIO_VER
    # ports:
    #   - "9000:9000"
    # volumes:
    #   - ./minio/config:/root/.minio
    #   - ./minio/data:/data
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://minio:9000/minio/health/live"]
      timeout: 5s
      retries: 60
      interval: 1s
  fakeservices.datajoint.io:
    <<: *net
    image: nginx:alpine
    environment:
      - URL=datajoint.io
      - SUBDOMAINS=fakeservices
      - MINIO_SERVER=http://minio:9000
    entrypoint: /entrypoint.sh
    healthcheck:
      test: wget --quiet --tries=1 --spider https://fakeservices.datajoint.io:443/minio/health/live || exit 1
      timeout: 5s
      retries: 300
      interval: 1s
    # ports:
    #   - "9000:9000"
    #   - "443:443"
    volumes:
      - ./tests/nginx/base.conf:/base.conf
      - ./tests/nginx/entrypoint.sh:/entrypoint.sh
      - ./tests/nginx/fullchain.pem:/certs/fullchain.pem
      - ./tests/nginx/privkey.pem:/certs/privkey.pem
networks:
  main:
